### 新規登録
POST http://localhost:5043/api/books
Content-Type: application/json

{
  "Title": "The Great Gatsby4",
  "Genre": 6,
  "TotalPages": 30,
  "InterestLevel": 4
}

### 1冊取得
GET http://localhost:5043/api/books/2

### 削除
DELETE http://localhost:5043/api/books/4

### 一覧取得・条件なし
GET http://localhost:5043/api/books

###
PUT http://localhost:5043/api/books/2/progress
Content-Type: application/json

{
   "CurrentPage": 100
}

### Sort
GET http://localhost:5043/api/books?field=Title&order=Ascending

### Filter + Sort
GET http://localhost:5043/api/books?minPages=100&field=TotalPages&order=Descending

### 不正なSort
GET http://localhost:5043/api/books?field=Title